HW8/HomeWork8/FirstApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'First-App'
urlpatterns = [
                  path('home/', views.home_view, name="home")
              ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HW8/HomeWork8/HomeWork8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FirstApp.urls'))
]

HW8/HomeWork8/FirstApp/models.py
from django.db import models


# Create your models here.


class SlideShowPost(models.Model):
    title = models.CharField(verbose_name='title of post', max_length=200)
    caption = models.CharField(verbose_name='caption', max_length=800)
    uploads = models.ImageField(verbose_name='image', blank=True, null=True)


class AboutPost(models.Model):
    text = models.TextField(verbose_name='text')


class Services(models.Model):
    created_date = models.DateTimeField(verbose_name="Date of Create", auto_now_add=True)
    title = models.CharField(verbose_name="Title", max_length=100)
    content = models.TextField(verbose_name="Body")


class ContactUs(models.Model):
    name = models.CharField(verbose_name='name', max_length=150)
    email = models.CharField(verbose_name='email', max_length=300)
    subject = models.CharField(verbose_name='subject', max_length=1000)
    message = models.TextField(verbose_name='message')

HW8/HomeWork8/FirstApp/forms.py
from django import forms

from . import models


class PostForm(forms.ModelForm):
    class Meta:
        model = models.ContactUs
        fields = [
            'name', 'email', 'subject', 'message'
        ]

HW8/HomeWork8/FirstApp/views.py
from django.shortcuts import render

from . import models, forms


# Create your views here.

def home_view(request):
    """
    it`s a view for home part of page!!!
    """
    slide_show_posts = models.SlideShowPost.objects.all()
    about_post = models.AboutPost.objects.all()
    services = models.Services.objects.all()
    form_instance = forms.PostForm()
    if request.method == 'POST':
        form_instance = forms.PostForm(data=request.POST)
        if form_instance.is_valid():
            form_instance.save()
    return render(request,
                  context={
                      "slide_show_posts": slide_show_posts,
                      "about_post": about_post,
                      "services_post": services,
                      "post_form": form_instance
                  },
                  template_name="FirstApp/home.html"
                  )

HW8/HomeWork8/FirstApp/templates/FirstApp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Selecao</title>
    <style>
        #header {
            font-size: 40pt;
        }

        #nav_items {
            font-size: 20pt;
        }
    </style>
</head>
<body>
{#NAVBAR`S CODE !!!! :#}
<nav class="navbar navbar-expand-xl navbar-dark " style="background-color: rgba(22,32,110,0.99)">
    <a id="header" class="navbar-brand mb-3 ml-4 h1 bp3-text-large " style="color: white" href="#">Selecao</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul id="nav_items" class="navbar-nav ">
            <li class="nav-item active">
                <a class="nav-link " style="color: white" href="{% url 'First-App:home' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: white" href="#About">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: white" href="#Services">Services</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: white" href="#">Portfolio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: white" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: white" href="#">Team</a>
            </li>
            <li class="nav-item dropdown show">
                <a class="nav-link dropdown-toggle" style="color: white" role="link" href="#"
                   id="navbarDropdownMenuLink"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Drop Down
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a id="nav_items" class="dropdown-item" href="#">Drop Down 1</a>
                    <div class="dropleft">
                        <a id="nav_items" class="dropdown-toggle" href="#"
                           data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Deep Drop Down
                        </a>
                        <div class="dropdown-menu" aria-labelledby="nav_items">
                            <a id="nav_items" class="dropdown-item" href="#">Deep Drop Down 1</a>
                            <a id="nav_items" class="dropdown-item" href="#">Deep Drop Down 2</a>
                            <a id="nav_items" class="dropdown-item" href="#">Deep Drop Down 3</a>
                        </div>
                    </div>
                    <a id="nav_items" class="dropdown-item" href="#">Drop Down 2</a>
                    <a id="nav_items" class="dropdown-item" href="#">Drop Down 3</a>
                    <a id="nav_items" class="dropdown-item" href="#">Drop Down 4</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link mr-5" style="color: white" href="#contact">Contact</a>
            </li>
        </ul>
    </div>
</nav>
{#SLIDE SHOW CODE !!!!! :#}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="Screenshot (19).png" alt="FirstSlide">
            <div class="carousel-caption d-none d-md-block">
                <h5 style="font-size: 50pt">ACTIVE POST</h5>
                <p style="font-size: 40pt">CAPTION!!!!!!!!!!</p>
            </div>
        </div>
        {% for post in slide_show_posts %}
            <div class="carousel-item ">
                <img class="d-block w-100" src={{ post.uploads.url }} alt="FirstSlide">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="font-size: 50pt">{{ post.title }}</h5>
                    <p style="font-size: 40pt">{{ post.caption }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{#page parts : #}
<div style="background-color: rgba(22,32,110,0.99) ; color: white">
    {#About code !!!!#}
    <div id="About">
        <h1 class="text-sm-left text-uppercase font-weight-light font-italic">ABOUT Us :</h1>
        {% for post in about_post %}
            <p style="font-size: 20pt" class="text-left text-lowercase font-weight-normal ">{{ post.text }}</p>
        {% endfor %}
    </div>
    {#Services code!!!!!#}
    <div id="Services">
        <h1 class="text-sm-left text-uppercase font-weight-light font-italic">Our Services :</h1>
        <div class="container">
            <div class="row mb-2">
                {% for post in services_post %}
                    <div class="col-md-4">
                        <h1 style="font-size: 30pt" class=" text-lowercase font-weight-normal ">{{ post.title }}</h1>
                        <p style="font-size: 20pt" class=" text-lowercase font-weight-normal ">{{ post.content }}</p>
                        <h6>{{ post.created_date }}</h6>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {#contact us code !!!!!!#}
    <div id="contact">
        <h1 class="text-sm-left text-uppercase font-weight-light font-italic">Contact Us Here :</h1>
        <div>
            <div class="container">
                <div class="row mb-2">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name">Your Name : </label>
                            <input type="text" id="name" class="form-control" name="name">
                        </div>
                        <div class="form-group">
                            <label for="subject">Your Subject : </label>
                            <input type="text" id="subject" class="form-control" name="subject">
                        </div>
                        <div class="form-group">
                            <label for="email">Your Email : </label>
                            <input type="text" id="email" class="form-control" name="email">
                        </div>
                        <div class="form-group">
                            <label for="message">Your Message : </label>
                            <textarea name="message" id="message" class="form-control" cols="80" rows="15"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <p style="color: #0c5460">ss</p>
</div>
{#finall part#}
<div style="background-color: black ; color: white">
    <h1 class="text-sm-center text-uppercase font-weight-bold font-italic">
        <a href="{% url 'First-App:home' %}">selecao</a>
    </h1>
    <p style="font-size: 20pt" class="text-center text-lowercase font-weight-normal ">We are SELECAO!!!</p>
    <p style="font-size: 10pt" class="text-center text-capitalize font-weight-normal ">Designed by AmirHossein Nejadkoorki</p>
    <p style="color: black">ss</p>
</div>


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>